import os

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# --- API ---
API_KEY    = os.getenv("BINANCE_API_KEY", "")
API_SECRET = os.getenv("BINANCE_API_SECRET", "")
LIVE_TRADING_APPROVED = False
REQUIRE_ONE_WAY_MODE = True
MARKET_ORDER_RESP_TYPE = "RESULT"
RECV_WINDOW_MS = 5000
ADJUST_FOR_TIME_DIFFERENCE = True
CREATE_ORDER_MAX_RETRIES = 2
PARTIAL_FILL_POLICY = "abort"  # "abort" or "accept"
BAR_AGE_GUARD_ENABLED = True
MAX_CLOSED_BAR_AGE_MULT = 1.25
TESTNET    = True   # False = canlı işlem

# --- Piyasa ---
SYMBOLS         = ["DOGE/USDT", "LINK/USDT", "TRX/USDT"]
SYMBOL          = "BTC/USDT"
TIMEFRAME       = "4h"
DAILY_TIMEFRAME = "1d"          # Yüksek TF trend filtresi
WEEKLY_TIMEFRAME = "1w"
LEVERAGE        = 10            # Growth 70 compound candidate
MARGIN_MODE     = "cross"       # Backtest currently models cross-style shared wallet

# --- Sermaye & Risk ---
CAPITAL_USDT         = 1000.0
RISK_PER_TRADE_PCT   = 0.04     # %4 of current portfolio equity on first open position
MAX_OPEN_POSITIONS   = 2
DAILY_LOSS_LIMIT_PCT = 0.06     # approx first+second corr-aware SL day guard
RISK_BASIS = "portfolio"        # "portfolio" = full equity, "symbol_sleeve" = equity / symbol count
CORRELATION_AWARE_SIZING_ENABLED = True
DYNAMIC_RISK_ENABLED = True
DYNAMIC_RISK_MIN_MULT = 0.50
DYNAMIC_RISK_MAX_MULT = 1.25
FINAL_RISK_MIN_MULT = 0.10
FINAL_RISK_MAX_MULT = 1.25
CALENDAR_RISK_ENABLED = True
CALENDAR_EVENT_FILE = "event_calendar.csv"
WEEKEND_RISK_MULT = 0.70
WEEKLY_OPEN_RISK_MULT = 0.75
FUNDING_RISK_MULT = 0.90
FUNDING_WINDOW_MINUTES = 30
DAILY_CLOSE_RISK_MULT = 0.85
DAILY_CLOSE_WINDOW_MINUTES = 60

# --- SL / TP (ATR çarpanı) ---
SL_ATR_MULT = 2.0
TP_ATR_MULT = 4.0
TRAIL_GIVEBACK = 0.15
TRAIL_GIVEBACK_STRONG = 0.25
TRAIL_WIDE_AFTER_R = 2.5

# --- Whale/wick protection ---
WICK_GUARD_ENABLED = True
WICK_GUARD_RANGE_ATR_MULT = 2.50
WICK_GUARD_WICK_BODY_RATIO = 2.50
WICK_GUARD_VOLUME_MULT = 2.00
SOFT_STOP_CLOSE_CONFIRM = True
HARD_STOP_EXTRA_ATR = 1.00
USE_MARK_PRICE_STOPS = True
USE_PRICE_PROTECT = True
ORDER_BOOK_GUARD_ENABLED = True
ORDER_BOOK_GUARD_FAIL_CLOSED = True
MAX_SPREAD_PCT = 0.0015
MIN_DEPTH_TO_NOTIONAL_MULT = 3.0
ORDER_BOOK_DEPTH_BAND_PCT = 0.0020

# --- Liquidation / hard-stop guard ---
LIQUIDATION_GUARD_ENABLED = False
MAINTENANCE_MARGIN_RATE = 0.005
LIQUIDATION_BUFFER_PCT = 0.015

# --- Rolling volume profile context ---
VOLUME_PROFILE_ENABLED = True
VOLUME_PROFILE_RISK_ENABLED = True
VOLUME_PROFILE_LOOKBACK = 120
VOLUME_PROFILE_MIN_BARS = 60
VOLUME_PROFILE_BINS = 48
VOLUME_PROFILE_VALUE_AREA_PCT = 0.70
VOLUME_PROFILE_NEAR_POC_PCT = 0.004
VOLUME_PROFILE_NARROW_VALUE_PCT = 0.018
VOLUME_PROFILE_MIN_MULT = 0.80
VOLUME_PROFILE_MAX_MULT = 1.08
VOLUME_PROFILE_BLOCK_CONTRA_VALUE = False

# --- Candlestick / price-action pattern context ---
PATTERN_SIGNALS_ENABLED = True
PATTERN_RISK_ENABLED = True
PATTERN_SWEEP_LOOKBACK = 20
PATTERN_WICK_BODY_RATIO = 2.0
PATTERN_MIN_WICK_RANGE_PCT = 0.45
PATTERN_IMPULSE_BODY_PCT = 0.65
PATTERN_IMPULSE_ATR_MULT = 1.15
PATTERN_VOLUME_MULT = 1.20
PATTERN_CONFIRM_THRESHOLD = 0.80
PATTERN_STRONG_THRESHOLD = 1.40
PATTERN_CONFIRM_MULT = 1.06
PATTERN_STRONG_CONFIRM_MULT = 1.12
PATTERN_CONTRA_MULT = 1.00
PATTERN_STRONG_CONTRA_MULT = 1.00
PATTERN_BLOCK_STRONG_CONTRA = False

# --- Futures flow context ---
# Public Binance futures flow data is mostly recent-window data. It is wired
# into live/testnet decisions and kept optional for long historical backtests.
FLOW_DATA_ENABLED = True
FLOW_RISK_ENABLED = True
FLOW_BACKTEST_ENABLED = False
FLOW_HISTORY_LIMIT = 500
FLOW_PERIOD = TIMEFRAME
FLOW_MIN_MULT = 0.85
FLOW_MAX_MULT = 1.08
FLOW_TAKER_BUY_ALIGNED = 0.56
FLOW_TAKER_BUY_CONTRA = 0.44
FLOW_TOP_RATIO_LONG = 1.15
FLOW_TOP_RATIO_SHORT = 0.85
FLOW_TOP_RATIO_CROWDED_LONG = 2.20
FLOW_TOP_RATIO_CROWDED_SHORT = 0.45
FLOW_OI_CHANGE_CONFIRM = 0.03
FLOW_OI_CHANGE_EXTREME = 0.12
FLOW_FUNDING_HIGH = 0.0005
FLOW_FUNDING_EXTREME = 0.0010
FLOW_MAX_AGE_MINUTES = 300

# --- Mature-bot add-ons (passive by default) ---
# These are intentionally disabled so the current strategy/backtest/paper
# behavior does not change until each layer proves net-positive.
PROTECTIONS_ENABLED = False
PROTECTION_COOLDOWN_CANDLES = 1
PROTECTION_STOPLOSS_LOOKBACK_CANDLES = 24
PROTECTION_STOPLOSS_TRADE_LIMIT = 3
PROTECTION_STOPLOSS_LOCK_CANDLES = 2
PROTECTION_LOW_PROFIT_LOOKBACK_CANDLES = 12
PROTECTION_LOW_PROFIT_TRADE_LIMIT = 3
PROTECTION_LOW_PROFIT_REQUIRED_PNL = 0.0
PROTECTION_LOW_PROFIT_LOCK_CANDLES = 2
PROTECTION_MAX_DRAWDOWN_PCT = 0.15
PROTECTION_MAX_DRAWDOWN_LOCK_CANDLES = 6

EXIT_LADDER_ENABLED = False
EXIT_LADDER_TP1_R = 1.0
EXIT_LADDER_TP1_FRACTION = 0.25
EXIT_LADDER_TP2_R = 2.0
EXIT_LADDER_TP2_FRACTION = 0.25
EXIT_LADDER_BREAKEVEN_AFTER_STEP = 1

PAIR_UNIVERSE_ENABLED = False
PAIR_UNIVERSE_MIN_BARS = 1000
PAIR_UNIVERSE_MIN_AVG_QUOTE_VOLUME = 5_000_000.0
PAIR_UNIVERSE_MAX_ATR_PCT = 0.08
PAIR_UNIVERSE_MIN_ATR_PCT = 0.003
PAIR_UNIVERSE_MAX_FUNDING_ABS = 0.0015
PAIR_UNIVERSE_MIN_SCORE = 0.0

TWAP_ENABLED = False
TWAP_MIN_NOTIONAL_USDT = 5_000.0
TWAP_SLICE_NOTIONAL_USDT = 1_000.0
TWAP_MAX_SLICES = 10
TWAP_INTERVAL_SECONDS = 30

OPS_HEARTBEAT_STALE_MINUTES = 180

# --- Backtest maliyet varsayımları ---
# Tarihsel funding verisi çekilemezse fallback olarak kullanılır.
DEFAULT_FUNDING_RATE_PER_8H = 0.0001
TAKER_FEE_RATE = 0.0004
ROUND_TRIP_FEE_RATE = TAKER_FEE_RATE * 2
SLIPPAGE_RATE_ROUND_TRIP = 0.0015

# --- Paper/testnet telemetry ---
PAPER_STATE_FILE = "paper_state.json"
PAPER_DECISIONS_CSV = "paper_decisions.csv"
PAPER_TRADES_CSV = "paper_trades.csv"
PAPER_EQUITY_CSV = "paper_equity.csv"
PAPER_ERRORS_CSV = "paper_errors.csv"
PAPER_HEARTBEAT_FILE = "paper_heartbeat.json"
PAPER_LOCK_FILE = "paper_runner.lock"
PAPER_START_BALANCE = CAPITAL_USDT
PAPER_ENTRY_SLIPPAGE_RATE = SLIPPAGE_RATE_ROUND_TRIP / 2
PAPER_EXIT_SLIPPAGE_RATE = SLIPPAGE_RATE_ROUND_TRIP / 2
PAPER_MAX_RETRIES = 3
PAPER_RETRY_BASE_SECONDS = 5
PAPER_ERROR_SLEEP_SECONDS = 300
PAPER_LOCK_STALE_MINUTES = 240
TESTNET_FILL_PROBE_NOTIONAL_USDT = 110.0
ORDER_EVENTS_JSONL = "order_events.jsonl"
LIVE_STATE_FILE = "live_state.json"
ALERTS_JSONL = "alerts.jsonl"

# --- Trend takip indikatörleri (eski mantık, bazı yardımcılar hala kullanılıyor) ---
EMA_FAST   = 21
EMA_SLOW   = 50
ADX_PERIOD = 14
ADX_THRESH = 20
RSI_PERIOD = 14
ATR_PERIOD = 14

# --- Donchian breakout (ana sinyal) ---
DONCHIAN_PERIOD = 20            # 4H mum sayısı (~3.3 gün)
DONCHIAN_EXIT   = 10            # Erken çıkış için daha sıkı kanal

# --- Hacim filtresi ---
VOLUME_MA_PERIOD = 20
VOLUME_MULT      = 1.5          # Kırılım barı hacmi >= 1.5 × ortalama

# --- 1D trend filtresi ---
DAILY_EMA_PERIOD = 50           # Günlük EMA50 — fiyat üstü ise long-only
WEEKLY_EMA_PERIOD = 30
REQUIRE_WEEKLY_TREND_ALIGNMENT = False
WEEKLY_TREND_RISK_ENABLED = False

# --- RSI aşırı bölge filtresi (kırılım sırasında pump/dump'ı engelle) ---
RSI_MAX_LONG  = 75              # Long sinyali için RSI <= 75
RSI_MIN_SHORT = 25              # Short sinyali için RSI >= 25

# --- Veri ---
WARMUP_BARS = 250               # 4H mum (Donchian + EMA50 + ATR ısınması)
